// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/tunnel/v1/tunnel.proto

package pb

import (
	_ "github.com/otterscale/otterscale-agent/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest contains the agent's cluster identity and tunnel port.
type RegisterRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cluster     *string                `protobuf:"bytes,1,opt,name=cluster"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetCluster() string {
	if x != nil {
		if x.xxx_hidden_Cluster != nil {
			return *x.xxx_hidden_Cluster
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) SetCluster(v string) {
	x.xxx_hidden_Cluster = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RegisterRequest) HasCluster() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterRequest) ClearCluster() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cluster = nil
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The cluster identifier this agent belongs to.
	Cluster *string
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cluster != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Cluster = b.Cluster
	}
	return m0
}

// RegisterResponse contains the server's fingerprint for the agent to verify the connection.
type RegisterResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Fingerprint *string                `protobuf:"bytes,1,opt,name=fingerprint"`
	xxx_hidden_TunnelPort  int32                  `protobuf:"varint,2,opt,name=tunnel_port,json=tunnelPort"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResponse) GetFingerprint() string {
	if x != nil {
		if x.xxx_hidden_Fingerprint != nil {
			return *x.xxx_hidden_Fingerprint
		}
		return ""
	}
	return ""
}

func (x *RegisterResponse) GetTunnelPort() int32 {
	if x != nil {
		return x.xxx_hidden_TunnelPort
	}
	return 0
}

func (x *RegisterResponse) SetFingerprint(v string) {
	x.xxx_hidden_Fingerprint = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RegisterResponse) SetTunnelPort(v int32) {
	x.xxx_hidden_TunnelPort = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RegisterResponse) HasFingerprint() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterResponse) HasTunnelPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterResponse) ClearFingerprint() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Fingerprint = nil
}

func (x *RegisterResponse) ClearTunnelPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TunnelPort = 0
}

type RegisterResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The server's tunnel fingerprint, used by the agent to verify the connection.
	Fingerprint *string
	// The port on the server side that will be mapped to this agent's local proxy.
	TunnelPort *int32
}

func (b0 RegisterResponse_builder) Build() *RegisterResponse {
	m0 := &RegisterResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Fingerprint != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Fingerprint = b.Fingerprint
	}
	if b.TunnelPort != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_TunnelPort = *b.TunnelPort
	}
	return m0
}

var File_api_tunnel_v1_tunnel_proto protoreflect.FileDescriptor

const file_api_tunnel_v1_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/tunnel/v1/tunnel.proto\x12\x14otterscale.tunnel.v1\x1a\x15api/annotations.proto\"+\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\"U\n" +
	"\x10RegisterResponse\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x1f\n" +
	"\vtunnel_port\x18\x02 \x01(\x05R\n" +
	"tunnelPort2\x81\x01\n" +
	"\rTunnelService\x12p\n" +
	"\bRegister\x12%.otterscale.tunnel.v1.RegisterRequest\x1a&.otterscale.tunnel.v1.RegisterResponse\"\x15\x8a\xdf\xd5\x1d\x10\n" +
	"\x0etunnel-enabledB9Z7github.com/otterscale/otterscale-agent/api/tunnel/v1;pbb\beditionsp\xe8\a"

var file_api_tunnel_v1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_tunnel_v1_tunnel_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: otterscale.tunnel.v1.RegisterRequest
	(*RegisterResponse)(nil), // 1: otterscale.tunnel.v1.RegisterResponse
}
var file_api_tunnel_v1_tunnel_proto_depIdxs = []int32{
	0, // 0: otterscale.tunnel.v1.TunnelService.Register:input_type -> otterscale.tunnel.v1.RegisterRequest
	1, // 1: otterscale.tunnel.v1.TunnelService.Register:output_type -> otterscale.tunnel.v1.RegisterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_tunnel_v1_tunnel_proto_init() }
func file_api_tunnel_v1_tunnel_proto_init() {
	if File_api_tunnel_v1_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tunnel_v1_tunnel_proto_rawDesc), len(file_api_tunnel_v1_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tunnel_v1_tunnel_proto_goTypes,
		DependencyIndexes: file_api_tunnel_v1_tunnel_proto_depIdxs,
		MessageInfos:      file_api_tunnel_v1_tunnel_proto_msgTypes,
	}.Build()
	File_api_tunnel_v1_tunnel_proto = out.File
	file_api_tunnel_v1_tunnel_proto_goTypes = nil
	file_api_tunnel_v1_tunnel_proto_depIdxs = nil
}
