// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/fleet/v1/fleet.proto

package pb

import (
	_ "github.com/otterscale/otterscale-agent/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cluster struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_AgentVersion *string                `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Cluster) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Cluster) GetAgentVersion() string {
	if x != nil {
		if x.xxx_hidden_AgentVersion != nil {
			return *x.xxx_hidden_AgentVersion
		}
		return ""
	}
	return ""
}

func (x *Cluster) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Cluster) SetAgentVersion(v string) {
	x.xxx_hidden_AgentVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Cluster) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Cluster) HasAgentVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Cluster) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Cluster) ClearAgentVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AgentVersion = nil
}

type Cluster_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The cluster name.
	Name *string
	// The version of the agent binary (e.g. "v1.2.3"), set at build time.
	AgentVersion *string
}

func (b0 Cluster_builder) Build() *Cluster {
	m0 := &Cluster{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.AgentVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_AgentVersion = b.AgentVersion
	}
	return m0
}

// ListClustersRequest is an empty request message for listing clusters.
type ListClustersRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersRequest) Reset() {
	*x = ListClustersRequest{}
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersRequest) ProtoMessage() {}

func (x *ListClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListClustersRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListClustersRequest_builder) Build() *ListClustersRequest {
	m0 := &ListClustersRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// ListClustersResponse contains the list of clusters the agent is registered to.
type ListClustersResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Clusters *[]*Cluster            `protobuf:"bytes,1,rep,name=clusters"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListClustersResponse) Reset() {
	*x = ListClustersResponse{}
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersResponse) ProtoMessage() {}

func (x *ListClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListClustersResponse) GetClusters() []*Cluster {
	if x != nil {
		if x.xxx_hidden_Clusters != nil {
			return *x.xxx_hidden_Clusters
		}
	}
	return nil
}

func (x *ListClustersResponse) SetClusters(v []*Cluster) {
	x.xxx_hidden_Clusters = &v
}

type ListClustersResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The list of clusters.
	Clusters []*Cluster
}

func (b0 ListClustersResponse_builder) Build() *ListClustersResponse {
	m0 := &ListClustersResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Clusters = &b.Clusters
	return m0
}

// RegisterRequest contains the agent's cluster identity and a CSR for
// mTLS certificate issuance.
type RegisterRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cluster      *string                `protobuf:"bytes,1,opt,name=cluster"`
	xxx_hidden_Csr          []byte                 `protobuf:"bytes,2,opt,name=csr"`
	xxx_hidden_AgentId      *string                `protobuf:"bytes,3,opt,name=agent_id,json=agentId"`
	xxx_hidden_AgentVersion *string                `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetCluster() string {
	if x != nil {
		if x.xxx_hidden_Cluster != nil {
			return *x.xxx_hidden_Cluster
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetCsr() []byte {
	if x != nil {
		return x.xxx_hidden_Csr
	}
	return nil
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		if x.xxx_hidden_AgentId != nil {
			return *x.xxx_hidden_AgentId
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		if x.xxx_hidden_AgentVersion != nil {
			return *x.xxx_hidden_AgentVersion
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) SetCluster(v string) {
	x.xxx_hidden_Cluster = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *RegisterRequest) SetCsr(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Csr = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *RegisterRequest) SetAgentId(v string) {
	x.xxx_hidden_AgentId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *RegisterRequest) SetAgentVersion(v string) {
	x.xxx_hidden_AgentVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *RegisterRequest) HasCluster() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterRequest) HasCsr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterRequest) HasAgentId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RegisterRequest) HasAgentVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RegisterRequest) ClearCluster() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cluster = nil
}

func (x *RegisterRequest) ClearCsr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Csr = nil
}

func (x *RegisterRequest) ClearAgentId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_AgentId = nil
}

func (x *RegisterRequest) ClearAgentVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_AgentVersion = nil
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The cluster identifier this agent belongs to.
	Cluster *string
	// PEM-encoded PKCS#10 certificate signing request. The server signs
	// this with its internal CA and returns the issued certificate.
	Csr []byte
	// The agent identifier this agent uses to register with the server.
	AgentId *string
	// The version of the agent binary (e.g. "v1.2.3"), set at build time.
	AgentVersion *string
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cluster != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Cluster = b.Cluster
	}
	if b.Csr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Csr = b.Csr
	}
	if b.AgentId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_AgentId = b.AgentId
	}
	if b.AgentVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_AgentVersion = b.AgentVersion
	}
	return m0
}

// GetAgentManifestRequest identifies the target cluster for which
// the agent installation manifest should be generated.
type GetAgentManifestRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cluster     *string                `protobuf:"bytes,1,opt,name=cluster"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetAgentManifestRequest) Reset() {
	*x = GetAgentManifestRequest{}
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentManifestRequest) ProtoMessage() {}

func (x *GetAgentManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAgentManifestRequest) GetCluster() string {
	if x != nil {
		if x.xxx_hidden_Cluster != nil {
			return *x.xxx_hidden_Cluster
		}
		return ""
	}
	return ""
}

func (x *GetAgentManifestRequest) SetCluster(v string) {
	x.xxx_hidden_Cluster = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetAgentManifestRequest) HasCluster() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetAgentManifestRequest) ClearCluster() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cluster = nil
}

type GetAgentManifestRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The cluster name the agent will register under.
	Cluster *string
}

func (b0 GetAgentManifestRequest_builder) Build() *GetAgentManifestRequest {
	m0 := &GetAgentManifestRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cluster != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Cluster = b.Cluster
	}
	return m0
}

// GetAgentManifestResponse contains the multi-document YAML manifest
// that can be applied via kubectl to install the agent.
type GetAgentManifestResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Manifest    *string                `protobuf:"bytes,1,opt,name=manifest"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetAgentManifestResponse) Reset() {
	*x = GetAgentManifestResponse{}
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentManifestResponse) ProtoMessage() {}

func (x *GetAgentManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAgentManifestResponse) GetManifest() string {
	if x != nil {
		if x.xxx_hidden_Manifest != nil {
			return *x.xxx_hidden_Manifest
		}
		return ""
	}
	return ""
}

func (x *GetAgentManifestResponse) SetManifest(v string) {
	x.xxx_hidden_Manifest = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetAgentManifestResponse) HasManifest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetAgentManifestResponse) ClearManifest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Manifest = nil
}

type GetAgentManifestResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Multi-document YAML containing Namespace, ServiceAccount,
	// ClusterRoleBinding, and Deployment resources.
	Manifest *string
}

func (b0 GetAgentManifestResponse_builder) Build() *GetAgentManifestResponse {
	m0 := &GetAgentManifestResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Manifest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Manifest = b.Manifest
	}
	return m0
}

// RegisterResponse contains a CA-signed certificate and the CA
// certificate so the agent can establish an mTLS tunnel connection.
type RegisterResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Endpoint      *string                `protobuf:"bytes,1,opt,name=endpoint"`
	xxx_hidden_Certificate   []byte                 `protobuf:"bytes,2,opt,name=certificate"`
	xxx_hidden_CaCertificate []byte                 `protobuf:"bytes,3,opt,name=ca_certificate,json=caCertificate"`
	xxx_hidden_ServerVersion *string                `protobuf:"bytes,4,opt,name=server_version,json=serverVersion"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_v1_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResponse) GetEndpoint() string {
	if x != nil {
		if x.xxx_hidden_Endpoint != nil {
			return *x.xxx_hidden_Endpoint
		}
		return ""
	}
	return ""
}

func (x *RegisterResponse) GetCertificate() []byte {
	if x != nil {
		return x.xxx_hidden_Certificate
	}
	return nil
}

func (x *RegisterResponse) GetCaCertificate() []byte {
	if x != nil {
		return x.xxx_hidden_CaCertificate
	}
	return nil
}

func (x *RegisterResponse) GetServerVersion() string {
	if x != nil {
		if x.xxx_hidden_ServerVersion != nil {
			return *x.xxx_hidden_ServerVersion
		}
		return ""
	}
	return ""
}

func (x *RegisterResponse) SetEndpoint(v string) {
	x.xxx_hidden_Endpoint = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *RegisterResponse) SetCertificate(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Certificate = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *RegisterResponse) SetCaCertificate(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_CaCertificate = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *RegisterResponse) SetServerVersion(v string) {
	x.xxx_hidden_ServerVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *RegisterResponse) HasEndpoint() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterResponse) HasCertificate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterResponse) HasCaCertificate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RegisterResponse) HasServerVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RegisterResponse) ClearEndpoint() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Endpoint = nil
}

func (x *RegisterResponse) ClearCertificate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Certificate = nil
}

func (x *RegisterResponse) ClearCaCertificate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CaCertificate = nil
}

func (x *RegisterResponse) ClearServerVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ServerVersion = nil
}

type RegisterResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The loopback endpoint reserved for this cluster tunnel.
	Endpoint *string
	// PEM-encoded X.509 certificate signed by the server's CA.
	Certificate []byte
	// PEM-encoded CA certificate for verifying the tunnel server.
	CaCertificate []byte
	// The version of the server binary (e.g. "v1.2.3"), set at build time.
	// Agents compare this against their own version to decide whether a
	// self-update is needed.
	ServerVersion *string
}

func (b0 RegisterResponse_builder) Build() *RegisterResponse {
	m0 := &RegisterResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Endpoint != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Endpoint = b.Endpoint
	}
	if b.Certificate != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Certificate = b.Certificate
	}
	if b.CaCertificate != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_CaCertificate = b.CaCertificate
	}
	if b.ServerVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_ServerVersion = b.ServerVersion
	}
	return m0
}

var File_api_fleet_v1_fleet_proto protoreflect.FileDescriptor

const file_api_fleet_v1_fleet_proto_rawDesc = "" +
	"\n" +
	"\x18api/fleet/v1/fleet.proto\x12\x13otterscale.fleet.v1\x1a\x15api/annotations.proto\"B\n" +
	"\aCluster\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\"\x15\n" +
	"\x13ListClustersRequest\"P\n" +
	"\x14ListClustersResponse\x128\n" +
	"\bclusters\x18\x01 \x03(\v2\x1c.otterscale.fleet.v1.ClusterR\bclusters\"}\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x10\n" +
	"\x03csr\x18\x02 \x01(\fR\x03csr\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\"3\n" +
	"\x17GetAgentManifestRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\"6\n" +
	"\x18GetAgentManifestResponse\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\tR\bmanifest\"\x9e\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12 \n" +
	"\vcertificate\x18\x02 \x01(\fR\vcertificate\x12%\n" +
	"\x0eca_certificate\x18\x03 \x01(\fR\rcaCertificate\x12%\n" +
	"\x0eserver_version\x18\x04 \x01(\tR\rserverVersion2\x83\x03\n" +
	"\fFleetService\x12y\n" +
	"\fListClusters\x12(.otterscale.fleet.v1.ListClustersRequest\x1a).otterscale.fleet.v1.ListClustersResponse\"\x14\x8a\xdf\xd5\x1d\x0f\n" +
	"\rfleet-enabled\x12m\n" +
	"\bRegister\x12$.otterscale.fleet.v1.RegisterRequest\x1a%.otterscale.fleet.v1.RegisterResponse\"\x14\x8a\xdf\xd5\x1d\x0f\n" +
	"\rfleet-enabled\x12\x88\x01\n" +
	"\x10GetAgentManifest\x12,.otterscale.fleet.v1.GetAgentManifestRequest\x1a-.otterscale.fleet.v1.GetAgentManifestResponse\"\x17\x8a\xdf\xd5\x1d\x0f\n" +
	"\rfleet-enabled\x90\x02\x01B8Z6github.com/otterscale/otterscale-agent/api/fleet/v1;pbb\beditionsp\xe8\a"

var file_api_fleet_v1_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_fleet_v1_fleet_proto_goTypes = []any{
	(*Cluster)(nil),                  // 0: otterscale.fleet.v1.Cluster
	(*ListClustersRequest)(nil),      // 1: otterscale.fleet.v1.ListClustersRequest
	(*ListClustersResponse)(nil),     // 2: otterscale.fleet.v1.ListClustersResponse
	(*RegisterRequest)(nil),          // 3: otterscale.fleet.v1.RegisterRequest
	(*GetAgentManifestRequest)(nil),  // 4: otterscale.fleet.v1.GetAgentManifestRequest
	(*GetAgentManifestResponse)(nil), // 5: otterscale.fleet.v1.GetAgentManifestResponse
	(*RegisterResponse)(nil),         // 6: otterscale.fleet.v1.RegisterResponse
}
var file_api_fleet_v1_fleet_proto_depIdxs = []int32{
	0, // 0: otterscale.fleet.v1.ListClustersResponse.clusters:type_name -> otterscale.fleet.v1.Cluster
	1, // 1: otterscale.fleet.v1.FleetService.ListClusters:input_type -> otterscale.fleet.v1.ListClustersRequest
	3, // 2: otterscale.fleet.v1.FleetService.Register:input_type -> otterscale.fleet.v1.RegisterRequest
	4, // 3: otterscale.fleet.v1.FleetService.GetAgentManifest:input_type -> otterscale.fleet.v1.GetAgentManifestRequest
	2, // 4: otterscale.fleet.v1.FleetService.ListClusters:output_type -> otterscale.fleet.v1.ListClustersResponse
	6, // 5: otterscale.fleet.v1.FleetService.Register:output_type -> otterscale.fleet.v1.RegisterResponse
	5, // 6: otterscale.fleet.v1.FleetService.GetAgentManifest:output_type -> otterscale.fleet.v1.GetAgentManifestResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_fleet_v1_fleet_proto_init() }
func file_api_fleet_v1_fleet_proto_init() {
	if File_api_fleet_v1_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_fleet_v1_fleet_proto_rawDesc), len(file_api_fleet_v1_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_fleet_v1_fleet_proto_goTypes,
		DependencyIndexes: file_api_fleet_v1_fleet_proto_depIdxs,
		MessageInfos:      file_api_fleet_v1_fleet_proto_msgTypes,
	}.Build()
	File_api_fleet_v1_fleet_proto = out.File
	file_api_fleet_v1_fleet_proto_goTypes = nil
	file_api_fleet_v1_fleet_proto_depIdxs = nil
}
