// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/otterscale/otterscale-agent/internal/app"
	"github.com/otterscale/otterscale-agent/internal/config"
	"github.com/otterscale/otterscale-agent/internal/core"
	"github.com/otterscale/otterscale-agent/internal/mux"
	"github.com/otterscale/otterscale-agent/internal/providers/chisel"
	"github.com/otterscale/otterscale-agent/internal/providers/kubernetes"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func wireCmd() (*cobra.Command, func(), error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	tunnelProvider, err := chisel.NewChiselService(configConfig)
	if err != nil {
		return nil, nil, err
	}
	kubernetesKubernetes := kubernetes.New(tunnelProvider)
	discoveryClient := kubernetes.NewDiscoveryClient(kubernetesKubernetes)
	resourceRepo := kubernetes.NewResourceRepo(kubernetesKubernetes)
	resourceUseCase := core.NewResourceUseCase(discoveryClient, resourceRepo)
	resourceService := app.NewResourceService(resourceUseCase)
	hub := mux.NewHub(resourceService)
	command, err := newCmd(configConfig, hub, tunnelProvider)
	if err != nil {
		return nil, nil, err
	}
	return command, func() {
	}, nil
}
