// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/otterscale/otterscale-agent/internal/app"
	"github.com/otterscale/otterscale-agent/internal/bootstrap"
	"github.com/otterscale/otterscale-agent/internal/cmd/agent"
	"github.com/otterscale/otterscale-agent/internal/cmd/server"
	"github.com/otterscale/otterscale-agent/internal/config"
	"github.com/otterscale/otterscale-agent/internal/core"
	"github.com/otterscale/otterscale-agent/internal/providers/chisel"
	"github.com/otterscale/otterscale-agent/internal/providers/kubernetes"
	"github.com/otterscale/otterscale-agent/internal/providers/otterscale"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

// wireCmd assembles the root Cobra command with configuration loaded.
func wireCmd() (*cobra.Command, func(), error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	command, err := newCmd(configConfig)
	if err != nil {
		return nil, nil, err
	}
	return command, func() {
	}, nil
}

// wireServer assembles a fully wired Server with all gRPC services,
// use-cases, and infrastructure providers. The version parameter is
// provided by the caller and flows through Wire to FleetUseCase.
// The config parameter provides the CA seed for mTLS certificate
// issuance via provideCA.
func wireServer(v core.Version, conf *config.Config) (*server.Server, func(), error) {
	ca, err := provideCA(conf)
	if err != nil {
		return nil, nil, err
	}
	service := chisel.NewService(ca)
	agentManifestConfig := provideAgentManifestConfig(conf)
	fleetUseCase := core.NewFleetUseCase(service, v, agentManifestConfig)
	fleetService := app.NewFleetService(fleetUseCase)
	kubernetesKubernetes := kubernetes.New(service)
	discoveryClient := kubernetes.NewDiscoveryClient(kubernetesKubernetes)
	resourceRepo := kubernetes.NewResourceRepo(kubernetesKubernetes)
	resourceUseCase := core.NewResourceUseCase(discoveryClient, resourceRepo)
	resourceService := app.NewResourceService(resourceUseCase)
	runtimeRepo := kubernetes.NewRuntimeRepo(kubernetesKubernetes)
	runtimeUseCase := core.NewRuntimeUseCase(discoveryClient, runtimeRepo)
	runtimeService := app.NewRuntimeService(runtimeUseCase)
	handler := server.NewHandler(fleetService, resourceService, runtimeService)
	serverServer := server.NewServer(handler, service, runtimeUseCase)
	return serverServer, func() {
	}, nil
}

// wireAgent assembles a fully wired Agent with its handler, fleet
// registrar, and bootstrapper. The version parameter is provided by
// the caller and flows through Wire to both FleetRegistrar and Agent.
func wireAgent(v core.Version) (*agent.Agent, func(), error) {
	handler := agent.NewHandler()
	tunnelConsumer, err := otterscale.NewFleetRegistrar(v)
	if err != nil {
		return nil, nil, err
	}
	restConfig, err := provideInClusterConfig()
	if err != nil {
		return nil, nil, err
	}
	bootstrapper, err := bootstrap.New(restConfig)
	if err != nil {
		return nil, nil, err
	}
	agentAgent := agent.NewAgent(handler, tunnelConsumer, v, bootstrapper)
	return agentAgent, func() {
	}, nil
}
