// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/otterscale/otterscale-agent/internal/app"
	"github.com/otterscale/otterscale-agent/internal/chisel"
	"github.com/otterscale/otterscale-agent/internal/config"
	"github.com/otterscale/otterscale-agent/internal/core"
	"github.com/otterscale/otterscale-agent/internal/kubernetes"
	"github.com/otterscale/otterscale-agent/internal/leader"
	"github.com/otterscale/otterscale-agent/internal/mux"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func wireCmd(bool2 bool) (*cobra.Command, func(), error) {
	configConfig := config.New()
	tunnelService := chisel.NewTunnelService(configConfig)
	elector, err := leader.ProvideElector()
	if err != nil {
		return nil, nil, err
	}
	resourceProxy := app.NewResourceProxy(configConfig, tunnelService, elector)
	hub := mux.NewHub(resourceProxy)
	kubernetesKubernetes := kubernetes.New(configConfig)
	discoveryRepo := kubernetes.NewDiscoveryRepo(kubernetesKubernetes)
	resourceRepo := kubernetes.NewResourceRepo(kubernetesKubernetes)
	resourceUseCase := core.NewResourceUseCase(discoveryRepo, resourceRepo)
	resourceService := app.NewResourceService(resourceUseCase)
	spoke := mux.NewSpoke(resourceService)
	command := newCmd(configConfig, hub, spoke, tunnelService, elector)
	return command, func() {
	}, nil
}
