// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/tunnel/v1/tunnel.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/otterscale/otterscale-agent/api/tunnel/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TunnelServiceName is the fully-qualified name of the TunnelService service.
	TunnelServiceName = "otterscale.tunnel.v1.TunnelService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TunnelServiceRegisterProcedure is the fully-qualified name of the TunnelService's Register RPC.
	TunnelServiceRegisterProcedure = "/otterscale.tunnel.v1.TunnelService/Register"
)

// TunnelServiceClient is a client for the otterscale.tunnel.v1.TunnelService service.
type TunnelServiceClient interface {
	// Register allows an agent to register itself with the tunnel server.
	// The agent sends its cluster identity and tunnel port; the server responds
	// with its fingerprint so the agent can verify the tunnel connection.
	// Authentication is provided via gRPC metadata (Basic Auth).
	Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error)
}

// NewTunnelServiceClient constructs a client for the otterscale.tunnel.v1.TunnelService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTunnelServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TunnelServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tunnelServiceMethods := v1.File_api_tunnel_v1_tunnel_proto.Services().ByName("TunnelService").Methods()
	return &tunnelServiceClient{
		register: connect.NewClient[v1.RegisterRequest, v1.RegisterResponse](
			httpClient,
			baseURL+TunnelServiceRegisterProcedure,
			connect.WithSchema(tunnelServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tunnelServiceClient implements TunnelServiceClient.
type tunnelServiceClient struct {
	register *connect.Client[v1.RegisterRequest, v1.RegisterResponse]
}

// Register calls otterscale.tunnel.v1.TunnelService.Register.
func (c *tunnelServiceClient) Register(ctx context.Context, req *v1.RegisterRequest) (*v1.RegisterResponse, error) {
	response, err := c.register.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// TunnelServiceHandler is an implementation of the otterscale.tunnel.v1.TunnelService service.
type TunnelServiceHandler interface {
	// Register allows an agent to register itself with the tunnel server.
	// The agent sends its cluster identity and tunnel port; the server responds
	// with its fingerprint so the agent can verify the tunnel connection.
	// Authentication is provided via gRPC metadata (Basic Auth).
	Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error)
}

// NewTunnelServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTunnelServiceHandler(svc TunnelServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tunnelServiceMethods := v1.File_api_tunnel_v1_tunnel_proto.Services().ByName("TunnelService").Methods()
	tunnelServiceRegisterHandler := connect.NewUnaryHandlerSimple(
		TunnelServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(tunnelServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	return "/otterscale.tunnel.v1.TunnelService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TunnelServiceRegisterProcedure:
			tunnelServiceRegisterHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTunnelServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTunnelServiceHandler struct{}

func (UnimplementedTunnelServiceHandler) Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otterscale.tunnel.v1.TunnelService.Register is not implemented"))
}
