// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/fleet/v1/fleet.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/otterscale/otterscale-agent/api/fleet/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FleetServiceName is the fully-qualified name of the FleetService service.
	FleetServiceName = "otterscale.fleet.v1.FleetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FleetServiceListClustersProcedure is the fully-qualified name of the FleetService's ListClusters
	// RPC.
	FleetServiceListClustersProcedure = "/otterscale.fleet.v1.FleetService/ListClusters"
	// FleetServiceRegisterProcedure is the fully-qualified name of the FleetService's Register RPC.
	FleetServiceRegisterProcedure = "/otterscale.fleet.v1.FleetService/Register"
	// FleetServiceGetAgentManifestProcedure is the fully-qualified name of the FleetService's
	// GetAgentManifest RPC.
	FleetServiceGetAgentManifestProcedure = "/otterscale.fleet.v1.FleetService/GetAgentManifest"
)

// FleetServiceClient is a client for the otterscale.fleet.v1.FleetService service.
type FleetServiceClient interface {
	// ListClusters returns all cluster identifiers that the current agent
	// is registered to. This is used to discover which clusters are available
	// for tunnel connections.
	ListClusters(context.Context, *v1.ListClustersRequest) (*v1.ListClustersResponse, error)
	// Register allows an agent to register itself with the tunnel server.
	// The agent sends its cluster identity and tunnel port; the server responds
	// with its fingerprint so the agent can verify the tunnel connection.
	Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error)
	// GetAgentManifest returns a multi-document YAML manifest for installing
	// the otterscale agent on a target Kubernetes cluster. The manifest
	// includes a Namespace, ServiceAccount, ClusterRoleBinding (binding the
	// caller to cluster-admin), and a Deployment running the agent.
	GetAgentManifest(context.Context, *v1.GetAgentManifestRequest) (*v1.GetAgentManifestResponse, error)
}

// NewFleetServiceClient constructs a client for the otterscale.fleet.v1.FleetService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFleetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FleetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fleetServiceMethods := v1.File_api_fleet_v1_fleet_proto.Services().ByName("FleetService").Methods()
	return &fleetServiceClient{
		listClusters: connect.NewClient[v1.ListClustersRequest, v1.ListClustersResponse](
			httpClient,
			baseURL+FleetServiceListClustersProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListClusters")),
			connect.WithClientOptions(opts...),
		),
		register: connect.NewClient[v1.RegisterRequest, v1.RegisterResponse](
			httpClient,
			baseURL+FleetServiceRegisterProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		getAgentManifest: connect.NewClient[v1.GetAgentManifestRequest, v1.GetAgentManifestResponse](
			httpClient,
			baseURL+FleetServiceGetAgentManifestProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("GetAgentManifest")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// fleetServiceClient implements FleetServiceClient.
type fleetServiceClient struct {
	listClusters     *connect.Client[v1.ListClustersRequest, v1.ListClustersResponse]
	register         *connect.Client[v1.RegisterRequest, v1.RegisterResponse]
	getAgentManifest *connect.Client[v1.GetAgentManifestRequest, v1.GetAgentManifestResponse]
}

// ListClusters calls otterscale.fleet.v1.FleetService.ListClusters.
func (c *fleetServiceClient) ListClusters(ctx context.Context, req *v1.ListClustersRequest) (*v1.ListClustersResponse, error) {
	response, err := c.listClusters.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Register calls otterscale.fleet.v1.FleetService.Register.
func (c *fleetServiceClient) Register(ctx context.Context, req *v1.RegisterRequest) (*v1.RegisterResponse, error) {
	response, err := c.register.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetAgentManifest calls otterscale.fleet.v1.FleetService.GetAgentManifest.
func (c *fleetServiceClient) GetAgentManifest(ctx context.Context, req *v1.GetAgentManifestRequest) (*v1.GetAgentManifestResponse, error) {
	response, err := c.getAgentManifest.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// FleetServiceHandler is an implementation of the otterscale.fleet.v1.FleetService service.
type FleetServiceHandler interface {
	// ListClusters returns all cluster identifiers that the current agent
	// is registered to. This is used to discover which clusters are available
	// for tunnel connections.
	ListClusters(context.Context, *v1.ListClustersRequest) (*v1.ListClustersResponse, error)
	// Register allows an agent to register itself with the tunnel server.
	// The agent sends its cluster identity and tunnel port; the server responds
	// with its fingerprint so the agent can verify the tunnel connection.
	Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error)
	// GetAgentManifest returns a multi-document YAML manifest for installing
	// the otterscale agent on a target Kubernetes cluster. The manifest
	// includes a Namespace, ServiceAccount, ClusterRoleBinding (binding the
	// caller to cluster-admin), and a Deployment running the agent.
	GetAgentManifest(context.Context, *v1.GetAgentManifestRequest) (*v1.GetAgentManifestResponse, error)
}

// NewFleetServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFleetServiceHandler(svc FleetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fleetServiceMethods := v1.File_api_fleet_v1_fleet_proto.Services().ByName("FleetService").Methods()
	fleetServiceListClustersHandler := connect.NewUnaryHandlerSimple(
		FleetServiceListClustersProcedure,
		svc.ListClusters,
		connect.WithSchema(fleetServiceMethods.ByName("ListClusters")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceRegisterHandler := connect.NewUnaryHandlerSimple(
		FleetServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(fleetServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceGetAgentManifestHandler := connect.NewUnaryHandlerSimple(
		FleetServiceGetAgentManifestProcedure,
		svc.GetAgentManifest,
		connect.WithSchema(fleetServiceMethods.ByName("GetAgentManifest")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/otterscale.fleet.v1.FleetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FleetServiceListClustersProcedure:
			fleetServiceListClustersHandler.ServeHTTP(w, r)
		case FleetServiceRegisterProcedure:
			fleetServiceRegisterHandler.ServeHTTP(w, r)
		case FleetServiceGetAgentManifestProcedure:
			fleetServiceGetAgentManifestHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFleetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFleetServiceHandler struct{}

func (UnimplementedFleetServiceHandler) ListClusters(context.Context, *v1.ListClustersRequest) (*v1.ListClustersResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otterscale.fleet.v1.FleetService.ListClusters is not implemented"))
}

func (UnimplementedFleetServiceHandler) Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otterscale.fleet.v1.FleetService.Register is not implemented"))
}

func (UnimplementedFleetServiceHandler) GetAgentManifest(context.Context, *v1.GetAgentManifestRequest) (*v1.GetAgentManifestResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otterscale.fleet.v1.FleetService.GetAgentManifest is not implemented"))
}
