// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/resource/v1/resource.proto

package pb

import (
	_ "github.com/otterscale/otterscale-agent/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type defines the possible types of events from Kubernetes watch.
type WatchEvent_Type int32

const (
	WatchEvent_TYPE_UNSPECIFIED WatchEvent_Type = 0
	WatchEvent_TYPE_ADDED       WatchEvent_Type = 1
	WatchEvent_TYPE_MODIFIED    WatchEvent_Type = 2
	WatchEvent_TYPE_DELETED     WatchEvent_Type = 3
	WatchEvent_TYPE_BOOKMARK    WatchEvent_Type = 4
	WatchEvent_TYPE_ERROR       WatchEvent_Type = 5
)

// Enum value maps for WatchEvent_Type.
var (
	WatchEvent_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_ADDED",
		2: "TYPE_MODIFIED",
		3: "TYPE_DELETED",
		4: "TYPE_BOOKMARK",
		5: "TYPE_ERROR",
	}
	WatchEvent_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_ADDED":       1,
		"TYPE_MODIFIED":    2,
		"TYPE_DELETED":     3,
		"TYPE_BOOKMARK":    4,
		"TYPE_ERROR":       5,
	}
)

func (x WatchEvent_Type) Enum() *WatchEvent_Type {
	p := new(WatchEvent_Type)
	*p = x
	return p
}

func (x WatchEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_resource_v1_resource_proto_enumTypes[0].Descriptor()
}

func (WatchEvent_Type) Type() protoreflect.EnumType {
	return &file_api_resource_v1_resource_proto_enumTypes[0]
}

func (x WatchEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// APIResource represents a Kubernetes API resource with its metadata.
type APIResource struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Group       *string                `protobuf:"bytes,1,opt,name=group"`
	xxx_hidden_Version     *string                `protobuf:"bytes,2,opt,name=version"`
	xxx_hidden_Resource    *string                `protobuf:"bytes,3,opt,name=resource"`
	xxx_hidden_Kind        *string                `protobuf:"bytes,4,opt,name=kind"`
	xxx_hidden_Namespaced  bool                   `protobuf:"varint,5,opt,name=namespaced"`
	xxx_hidden_Verbs       []string               `protobuf:"bytes,6,rep,name=verbs"`
	xxx_hidden_ShortNames  []string               `protobuf:"bytes,7,rep,name=short_names,json=shortNames"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *APIResource) Reset() {
	*x = APIResource{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResource) ProtoMessage() {}

func (x *APIResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *APIResource) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *APIResource) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *APIResource) GetResource() string {
	if x != nil {
		if x.xxx_hidden_Resource != nil {
			return *x.xxx_hidden_Resource
		}
		return ""
	}
	return ""
}

func (x *APIResource) GetKind() string {
	if x != nil {
		if x.xxx_hidden_Kind != nil {
			return *x.xxx_hidden_Kind
		}
		return ""
	}
	return ""
}

func (x *APIResource) GetNamespaced() bool {
	if x != nil {
		return x.xxx_hidden_Namespaced
	}
	return false
}

func (x *APIResource) GetVerbs() []string {
	if x != nil {
		return x.xxx_hidden_Verbs
	}
	return nil
}

func (x *APIResource) GetShortNames() []string {
	if x != nil {
		return x.xxx_hidden_ShortNames
	}
	return nil
}

func (x *APIResource) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *APIResource) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *APIResource) SetResource(v string) {
	x.xxx_hidden_Resource = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *APIResource) SetKind(v string) {
	x.xxx_hidden_Kind = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *APIResource) SetNamespaced(v bool) {
	x.xxx_hidden_Namespaced = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *APIResource) SetVerbs(v []string) {
	x.xxx_hidden_Verbs = v
}

func (x *APIResource) SetShortNames(v []string) {
	x.xxx_hidden_ShortNames = v
}

func (x *APIResource) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *APIResource) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *APIResource) HasResource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *APIResource) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *APIResource) HasNamespaced() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *APIResource) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Group = nil
}

func (x *APIResource) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = nil
}

func (x *APIResource) ClearResource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Resource = nil
}

func (x *APIResource) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Kind = nil
}

func (x *APIResource) ClearNamespaced() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Namespaced = false
}

type APIResource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Group      *string
	Version    *string
	Resource   *string
	Kind       *string
	Namespaced *bool
	Verbs      []string
	ShortNames []string
}

func (b0 APIResource_builder) Build() *APIResource {
	m0 := &APIResource{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Group = b.Group
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Version = b.Version
	}
	if b.Resource != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Resource = b.Resource
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Kind = b.Kind
	}
	if b.Namespaced != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Namespaced = *b.Namespaced
	}
	x.xxx_hidden_Verbs = b.Verbs
	x.xxx_hidden_ShortNames = b.ShortNames
	return m0
}

// DiscoveryRequest defines the parameters for discovering API resources.
type DiscoveryRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cluster     *string                `protobuf:"bytes,1,opt,name=cluster"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiscoveryRequest) GetCluster() string {
	if x != nil {
		if x.xxx_hidden_Cluster != nil {
			return *x.xxx_hidden_Cluster
		}
		return ""
	}
	return ""
}

func (x *DiscoveryRequest) SetCluster(v string) {
	x.xxx_hidden_Cluster = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DiscoveryRequest) HasCluster() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DiscoveryRequest) ClearCluster() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cluster = nil
}

type DiscoveryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The target Kubernetes cluster identifier.
	Cluster *string
}

func (b0 DiscoveryRequest_builder) Build() *DiscoveryRequest {
	m0 := &DiscoveryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cluster != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Cluster = b.Cluster
	}
	return m0
}

// DiscoveryResponse contains the list of available API resources in the cluster.
type DiscoveryResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ApiResources *[]*APIResource        `protobuf:"bytes,1,rep,name=api_resources,json=apiResources"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiscoveryResponse) GetApiResources() []*APIResource {
	if x != nil {
		if x.xxx_hidden_ApiResources != nil {
			return *x.xxx_hidden_ApiResources
		}
	}
	return nil
}

func (x *DiscoveryResponse) SetApiResources(v []*APIResource) {
	x.xxx_hidden_ApiResources = &v
}

type DiscoveryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The list of available API resources in the cluster.
	ApiResources []*APIResource
}

func (b0 DiscoveryResponse_builder) Build() *DiscoveryResponse {
	m0 := &DiscoveryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ApiResources = &b.ApiResources
	return m0
}

// SchemaRequest defines the parameters to retrieve the schema of a specific GVR.
type SchemaRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cluster     *string                `protobuf:"bytes,1,opt,name=cluster"`
	xxx_hidden_Group       *string                `protobuf:"bytes,2,opt,name=group"`
	xxx_hidden_Version     *string                `protobuf:"bytes,3,opt,name=version"`
	xxx_hidden_Kind        *string                `protobuf:"bytes,4,opt,name=kind"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SchemaRequest) Reset() {
	*x = SchemaRequest{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRequest) ProtoMessage() {}

func (x *SchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SchemaRequest) GetCluster() string {
	if x != nil {
		if x.xxx_hidden_Cluster != nil {
			return *x.xxx_hidden_Cluster
		}
		return ""
	}
	return ""
}

func (x *SchemaRequest) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *SchemaRequest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *SchemaRequest) GetKind() string {
	if x != nil {
		if x.xxx_hidden_Kind != nil {
			return *x.xxx_hidden_Kind
		}
		return ""
	}
	return ""
}

func (x *SchemaRequest) SetCluster(v string) {
	x.xxx_hidden_Cluster = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *SchemaRequest) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *SchemaRequest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *SchemaRequest) SetKind(v string) {
	x.xxx_hidden_Kind = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *SchemaRequest) HasCluster() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SchemaRequest) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SchemaRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SchemaRequest) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SchemaRequest) ClearCluster() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cluster = nil
}

func (x *SchemaRequest) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Group = nil
}

func (x *SchemaRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = nil
}

func (x *SchemaRequest) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Kind = nil
}

type SchemaRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The target Kubernetes cluster identifier.
	Cluster *string
	// Kubernetes API Group (e.g., "apps" for Deployments, "" for core resources like Pods).
	Group *string
	// Kubernetes API Version (e.g., "v1").
	Version *string
	// Kubernetes API Kind (e,g, "Pod").
	Kind *string
}

func (b0 SchemaRequest_builder) Build() *SchemaRequest {
	m0 := &SchemaRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cluster != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Cluster = b.Cluster
	}
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Group = b.Group
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Version = b.Version
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Kind = b.Kind
	}
	return m0
}

// Resource represents a single Kubernetes object serialized as a JSON string.
type Resource struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Object *structpb.Struct       `protobuf:"bytes,1,opt,name=object"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Resource) GetObject() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_Object
	}
	return nil
}

func (x *Resource) SetObject(v *structpb.Struct) {
	x.xxx_hidden_Object = v
}

func (x *Resource) HasObject() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Object != nil
}

func (x *Resource) ClearObject() {
	x.xxx_hidden_Object = nil
}

type Resource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The full JSON representation of the Kubernetes object.
	// Note: Backend may strip managedFields to reduce payload size.
	Object *structpb.Struct
}

func (b0 Resource_builder) Build() *Resource {
	m0 := &Resource{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Object = b.Object
	return m0
}

// ListRequest defines the parameters for querying multiple resources.
type ListRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cluster       *string                `protobuf:"bytes,1,opt,name=cluster"`
	xxx_hidden_Group         *string                `protobuf:"bytes,2,opt,name=group"`
	xxx_hidden_Version       *string                `protobuf:"bytes,3,opt,name=version"`
	xxx_hidden_Resource      *string                `protobuf:"bytes,4,opt,name=resource"`
	xxx_hidden_Namespace     *string                `protobuf:"bytes,5,opt,name=namespace"`
	xxx_hidden_LabelSelector *string                `protobuf:"bytes,6,opt,name=label_selector,json=labelSelector"`
	xxx_hidden_FieldSelector *string                `protobuf:"bytes,7,opt,name=field_selector,json=fieldSelector"`
	xxx_hidden_Limit         int64                  `protobuf:"varint,8,opt,name=limit"`
	xxx_hidden_Continue      *string                `protobuf:"bytes,9,opt,name=continue"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRequest) GetCluster() string {
	if x != nil {
		if x.xxx_hidden_Cluster != nil {
			return *x.xxx_hidden_Cluster
		}
		return ""
	}
	return ""
}

func (x *ListRequest) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *ListRequest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *ListRequest) GetResource() string {
	if x != nil {
		if x.xxx_hidden_Resource != nil {
			return *x.xxx_hidden_Resource
		}
		return ""
	}
	return ""
}

func (x *ListRequest) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *ListRequest) GetLabelSelector() string {
	if x != nil {
		if x.xxx_hidden_LabelSelector != nil {
			return *x.xxx_hidden_LabelSelector
		}
		return ""
	}
	return ""
}

func (x *ListRequest) GetFieldSelector() string {
	if x != nil {
		if x.xxx_hidden_FieldSelector != nil {
			return *x.xxx_hidden_FieldSelector
		}
		return ""
	}
	return ""
}

func (x *ListRequest) GetLimit() int64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListRequest) GetContinue() string {
	if x != nil {
		if x.xxx_hidden_Continue != nil {
			return *x.xxx_hidden_Continue
		}
		return ""
	}
	return ""
}

func (x *ListRequest) SetCluster(v string) {
	x.xxx_hidden_Cluster = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *ListRequest) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *ListRequest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *ListRequest) SetResource(v string) {
	x.xxx_hidden_Resource = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *ListRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *ListRequest) SetLabelSelector(v string) {
	x.xxx_hidden_LabelSelector = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *ListRequest) SetFieldSelector(v string) {
	x.xxx_hidden_FieldSelector = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *ListRequest) SetLimit(v int64) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *ListRequest) SetContinue(v string) {
	x.xxx_hidden_Continue = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *ListRequest) HasCluster() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListRequest) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListRequest) HasResource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ListRequest) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ListRequest) HasLabelSelector() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ListRequest) HasFieldSelector() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ListRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ListRequest) HasContinue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *ListRequest) ClearCluster() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cluster = nil
}

func (x *ListRequest) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Group = nil
}

func (x *ListRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = nil
}

func (x *ListRequest) ClearResource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Resource = nil
}

func (x *ListRequest) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Namespace = nil
}

func (x *ListRequest) ClearLabelSelector() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_LabelSelector = nil
}

func (x *ListRequest) ClearFieldSelector() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_FieldSelector = nil
}

func (x *ListRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Limit = 0
}

func (x *ListRequest) ClearContinue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Continue = nil
}

type ListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The target Kubernetes cluster identifier.
	Cluster *string
	// Kubernetes API Group (e.g., "apps" for Deployments, "" for core resources like Pods).
	Group *string
	// Kubernetes API Version (e.g., "v1").
	Version *string
	// Kubernetes API Resource name in plural (e.g., "pods", "deployments").
	Resource *string
	// The namespace to query. If empty, the request may target all namespaces depending on cluster permissions.
	Namespace *string
	// A selector to restrict the list of returned objects by their labels.
	LabelSelector *string
	// A selector to restrict the list of returned objects by their fields (e.g., "status.phase=Running").
	FieldSelector *string
	// The maximum number of items to return in a single page.
	Limit *int64
	// The continue token for pagination, retrieved from a previous ListResponse.
	Continue *string
}

func (b0 ListRequest_builder) Build() *ListRequest {
	m0 := &ListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cluster != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_Cluster = b.Cluster
	}
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Group = b.Group
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Version = b.Version
	}
	if b.Resource != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Resource = b.Resource
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.LabelSelector != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_LabelSelector = b.LabelSelector
	}
	if b.FieldSelector != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_FieldSelector = b.FieldSelector
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Continue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_Continue = b.Continue
	}
	return m0
}

// ListResponse contains the requested list of resources and pagination metadata.
type ListResponse struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResourceVersion    *string                `protobuf:"bytes,1,opt,name=resource_version,json=resourceVersion"`
	xxx_hidden_Continue           *string                `protobuf:"bytes,2,opt,name=continue"`
	xxx_hidden_RemainingItemCount int64                  `protobuf:"varint,3,opt,name=remaining_item_count,json=remainingItemCount"`
	xxx_hidden_Items              *[]*Resource           `protobuf:"bytes,4,rep,name=items"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListResponse) GetResourceVersion() string {
	if x != nil {
		if x.xxx_hidden_ResourceVersion != nil {
			return *x.xxx_hidden_ResourceVersion
		}
		return ""
	}
	return ""
}

func (x *ListResponse) GetContinue() string {
	if x != nil {
		if x.xxx_hidden_Continue != nil {
			return *x.xxx_hidden_Continue
		}
		return ""
	}
	return ""
}

func (x *ListResponse) GetRemainingItemCount() int64 {
	if x != nil {
		return x.xxx_hidden_RemainingItemCount
	}
	return 0
}

func (x *ListResponse) GetItems() []*Resource {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *ListResponse) SetResourceVersion(v string) {
	x.xxx_hidden_ResourceVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ListResponse) SetContinue(v string) {
	x.xxx_hidden_Continue = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ListResponse) SetRemainingItemCount(v int64) {
	x.xxx_hidden_RemainingItemCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ListResponse) SetItems(v []*Resource) {
	x.xxx_hidden_Items = &v
}

func (x *ListResponse) HasResourceVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListResponse) HasContinue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListResponse) HasRemainingItemCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListResponse) ClearResourceVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ResourceVersion = nil
}

func (x *ListResponse) ClearContinue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Continue = nil
}

func (x *ListResponse) ClearRemainingItemCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RemainingItemCount = 0
}

type ListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The resourceVersion of the list, used to initiate a Watch from a specific point in time.
	ResourceVersion *string
	// A token used to retrieve the next page of results. Empty if no more pages exist.
	Continue *string
	// The estimated number of items remaining if pagination is used.
	RemainingItemCount *int64
	// The list of resources found.
	Items []*Resource
}

func (b0 ListResponse_builder) Build() *ListResponse {
	m0 := &ListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ResourceVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ResourceVersion = b.ResourceVersion
	}
	if b.Continue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Continue = b.Continue
	}
	if b.RemainingItemCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_RemainingItemCount = *b.RemainingItemCount
	}
	x.xxx_hidden_Items = &b.Items
	return m0
}

// GetRequest defines the parameters to fetch a single object.
type GetRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cluster     *string                `protobuf:"bytes,1,opt,name=cluster"`
	xxx_hidden_Group       *string                `protobuf:"bytes,2,opt,name=group"`
	xxx_hidden_Version     *string                `protobuf:"bytes,3,opt,name=version"`
	xxx_hidden_Resource    *string                `protobuf:"bytes,4,opt,name=resource"`
	xxx_hidden_Namespace   *string                `protobuf:"bytes,5,opt,name=namespace"`
	xxx_hidden_Name        *string                `protobuf:"bytes,6,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRequest) GetCluster() string {
	if x != nil {
		if x.xxx_hidden_Cluster != nil {
			return *x.xxx_hidden_Cluster
		}
		return ""
	}
	return ""
}

func (x *GetRequest) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *GetRequest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *GetRequest) GetResource() string {
	if x != nil {
		if x.xxx_hidden_Resource != nil {
			return *x.xxx_hidden_Resource
		}
		return ""
	}
	return ""
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *GetRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *GetRequest) SetCluster(v string) {
	x.xxx_hidden_Cluster = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *GetRequest) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *GetRequest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *GetRequest) SetResource(v string) {
	x.xxx_hidden_Resource = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *GetRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *GetRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *GetRequest) HasCluster() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetRequest) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetRequest) HasResource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetRequest) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *GetRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *GetRequest) ClearCluster() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cluster = nil
}

func (x *GetRequest) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Group = nil
}

func (x *GetRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = nil
}

func (x *GetRequest) ClearResource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Resource = nil
}

func (x *GetRequest) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Namespace = nil
}

func (x *GetRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Name = nil
}

type GetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cluster   *string
	Group     *string
	Version   *string
	Resource  *string
	Namespace *string
	Name      *string
}

func (b0 GetRequest_builder) Build() *GetRequest {
	m0 := &GetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cluster != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Cluster = b.Cluster
	}
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Group = b.Group
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Version = b.Version
	}
	if b.Resource != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Resource = b.Resource
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

// CreateRequest defines the parameters for creating a new object.
type CreateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cluster     *string                `protobuf:"bytes,1,opt,name=cluster"`
	xxx_hidden_Group       *string                `protobuf:"bytes,2,opt,name=group"`
	xxx_hidden_Version     *string                `protobuf:"bytes,3,opt,name=version"`
	xxx_hidden_Resource    *string                `protobuf:"bytes,4,opt,name=resource"`
	xxx_hidden_Namespace   *string                `protobuf:"bytes,5,opt,name=namespace"`
	xxx_hidden_Manifest    []byte                 `protobuf:"bytes,6,opt,name=manifest"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateRequest) GetCluster() string {
	if x != nil {
		if x.xxx_hidden_Cluster != nil {
			return *x.xxx_hidden_Cluster
		}
		return ""
	}
	return ""
}

func (x *CreateRequest) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *CreateRequest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *CreateRequest) GetResource() string {
	if x != nil {
		if x.xxx_hidden_Resource != nil {
			return *x.xxx_hidden_Resource
		}
		return ""
	}
	return ""
}

func (x *CreateRequest) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *CreateRequest) GetManifest() []byte {
	if x != nil {
		return x.xxx_hidden_Manifest
	}
	return nil
}

func (x *CreateRequest) SetCluster(v string) {
	x.xxx_hidden_Cluster = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *CreateRequest) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *CreateRequest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *CreateRequest) SetResource(v string) {
	x.xxx_hidden_Resource = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *CreateRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *CreateRequest) SetManifest(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Manifest = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *CreateRequest) HasCluster() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateRequest) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateRequest) HasResource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateRequest) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CreateRequest) HasManifest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CreateRequest) ClearCluster() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cluster = nil
}

func (x *CreateRequest) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Group = nil
}

func (x *CreateRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = nil
}

func (x *CreateRequest) ClearResource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Resource = nil
}

func (x *CreateRequest) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Namespace = nil
}

func (x *CreateRequest) ClearManifest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Manifest = nil
}

type CreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cluster   *string
	Group     *string
	Version   *string
	Resource  *string
	Namespace *string
	// The full manifest of the object to be created in YAML format.
	Manifest []byte
}

func (b0 CreateRequest_builder) Build() *CreateRequest {
	m0 := &CreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cluster != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Cluster = b.Cluster
	}
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Group = b.Group
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Version = b.Version
	}
	if b.Resource != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Resource = b.Resource
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.Manifest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Manifest = b.Manifest
	}
	return m0
}

// ApplyRequest defines the parameters for Server-Side Apply (SSA).
type ApplyRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cluster      *string                `protobuf:"bytes,1,opt,name=cluster"`
	xxx_hidden_Group        *string                `protobuf:"bytes,2,opt,name=group"`
	xxx_hidden_Version      *string                `protobuf:"bytes,3,opt,name=version"`
	xxx_hidden_Resource     *string                `protobuf:"bytes,4,opt,name=resource"`
	xxx_hidden_Namespace    *string                `protobuf:"bytes,5,opt,name=namespace"`
	xxx_hidden_Name         *string                `protobuf:"bytes,6,opt,name=name"`
	xxx_hidden_Manifest     []byte                 `protobuf:"bytes,7,opt,name=manifest"`
	xxx_hidden_Force        bool                   `protobuf:"varint,8,opt,name=force"`
	xxx_hidden_FieldManager *string                `protobuf:"bytes,9,opt,name=field_manager,json=fieldManager"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ApplyRequest) GetCluster() string {
	if x != nil {
		if x.xxx_hidden_Cluster != nil {
			return *x.xxx_hidden_Cluster
		}
		return ""
	}
	return ""
}

func (x *ApplyRequest) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *ApplyRequest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *ApplyRequest) GetResource() string {
	if x != nil {
		if x.xxx_hidden_Resource != nil {
			return *x.xxx_hidden_Resource
		}
		return ""
	}
	return ""
}

func (x *ApplyRequest) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *ApplyRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ApplyRequest) GetManifest() []byte {
	if x != nil {
		return x.xxx_hidden_Manifest
	}
	return nil
}

func (x *ApplyRequest) GetForce() bool {
	if x != nil {
		return x.xxx_hidden_Force
	}
	return false
}

func (x *ApplyRequest) GetFieldManager() string {
	if x != nil {
		if x.xxx_hidden_FieldManager != nil {
			return *x.xxx_hidden_FieldManager
		}
		return ""
	}
	return ""
}

func (x *ApplyRequest) SetCluster(v string) {
	x.xxx_hidden_Cluster = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *ApplyRequest) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *ApplyRequest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *ApplyRequest) SetResource(v string) {
	x.xxx_hidden_Resource = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *ApplyRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *ApplyRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *ApplyRequest) SetManifest(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Manifest = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *ApplyRequest) SetForce(v bool) {
	x.xxx_hidden_Force = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *ApplyRequest) SetFieldManager(v string) {
	x.xxx_hidden_FieldManager = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *ApplyRequest) HasCluster() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ApplyRequest) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ApplyRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ApplyRequest) HasResource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ApplyRequest) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ApplyRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ApplyRequest) HasManifest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ApplyRequest) HasForce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ApplyRequest) HasFieldManager() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *ApplyRequest) ClearCluster() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cluster = nil
}

func (x *ApplyRequest) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Group = nil
}

func (x *ApplyRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = nil
}

func (x *ApplyRequest) ClearResource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Resource = nil
}

func (x *ApplyRequest) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Namespace = nil
}

func (x *ApplyRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Name = nil
}

func (x *ApplyRequest) ClearManifest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Manifest = nil
}

func (x *ApplyRequest) ClearForce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Force = false
}

func (x *ApplyRequest) ClearFieldManager() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_FieldManager = nil
}

type ApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cluster   *string
	Group     *string
	Version   *string
	Resource  *string
	Namespace *string
	Name      *string
	// A partial or YAML manifest in JSON format to be merged by the API server.
	Manifest []byte
	Force    *bool
	// Identifies the entity managing the fields (e.g., "otterscale-web-ui"). Required for SSA.
	FieldManager *string
}

func (b0 ApplyRequest_builder) Build() *ApplyRequest {
	m0 := &ApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cluster != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_Cluster = b.Cluster
	}
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Group = b.Group
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Version = b.Version
	}
	if b.Resource != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Resource = b.Resource
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Name = b.Name
	}
	if b.Manifest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_Manifest = b.Manifest
	}
	if b.Force != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_Force = *b.Force
	}
	if b.FieldManager != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_FieldManager = b.FieldManager
	}
	return m0
}

// DeleteRequest defines the parameters to remove an object.
type DeleteRequest struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cluster            *string                `protobuf:"bytes,1,opt,name=cluster"`
	xxx_hidden_Group              *string                `protobuf:"bytes,2,opt,name=group"`
	xxx_hidden_Version            *string                `protobuf:"bytes,3,opt,name=version"`
	xxx_hidden_Resource           *string                `protobuf:"bytes,4,opt,name=resource"`
	xxx_hidden_Namespace          *string                `protobuf:"bytes,5,opt,name=namespace"`
	xxx_hidden_Name               *string                `protobuf:"bytes,6,opt,name=name"`
	xxx_hidden_GracePeriodSeconds int64                  `protobuf:"varint,7,opt,name=grace_period_seconds,json=gracePeriodSeconds"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRequest) GetCluster() string {
	if x != nil {
		if x.xxx_hidden_Cluster != nil {
			return *x.xxx_hidden_Cluster
		}
		return ""
	}
	return ""
}

func (x *DeleteRequest) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *DeleteRequest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *DeleteRequest) GetResource() string {
	if x != nil {
		if x.xxx_hidden_Resource != nil {
			return *x.xxx_hidden_Resource
		}
		return ""
	}
	return ""
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *DeleteRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *DeleteRequest) GetGracePeriodSeconds() int64 {
	if x != nil {
		return x.xxx_hidden_GracePeriodSeconds
	}
	return 0
}

func (x *DeleteRequest) SetCluster(v string) {
	x.xxx_hidden_Cluster = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *DeleteRequest) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *DeleteRequest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *DeleteRequest) SetResource(v string) {
	x.xxx_hidden_Resource = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *DeleteRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *DeleteRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *DeleteRequest) SetGracePeriodSeconds(v int64) {
	x.xxx_hidden_GracePeriodSeconds = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *DeleteRequest) HasCluster() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteRequest) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeleteRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DeleteRequest) HasResource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DeleteRequest) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *DeleteRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *DeleteRequest) HasGracePeriodSeconds() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *DeleteRequest) ClearCluster() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cluster = nil
}

func (x *DeleteRequest) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Group = nil
}

func (x *DeleteRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = nil
}

func (x *DeleteRequest) ClearResource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Resource = nil
}

func (x *DeleteRequest) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Namespace = nil
}

func (x *DeleteRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Name = nil
}

func (x *DeleteRequest) ClearGracePeriodSeconds() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_GracePeriodSeconds = 0
}

type DeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cluster            *string
	Group              *string
	Version            *string
	Resource           *string
	Namespace          *string
	Name               *string
	GracePeriodSeconds *int64
}

func (b0 DeleteRequest_builder) Build() *DeleteRequest {
	m0 := &DeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cluster != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Cluster = b.Cluster
	}
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Group = b.Group
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Version = b.Version
	}
	if b.Resource != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Resource = b.Resource
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_Name = b.Name
	}
	if b.GracePeriodSeconds != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_GracePeriodSeconds = *b.GracePeriodSeconds
	}
	return m0
}

// WatchRequest defines the parameters to start a streaming watch.
type WatchRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cluster         *string                `protobuf:"bytes,1,opt,name=cluster"`
	xxx_hidden_Group           *string                `protobuf:"bytes,2,opt,name=group"`
	xxx_hidden_Version         *string                `protobuf:"bytes,3,opt,name=version"`
	xxx_hidden_Resource        *string                `protobuf:"bytes,4,opt,name=resource"`
	xxx_hidden_Namespace       *string                `protobuf:"bytes,5,opt,name=namespace"`
	xxx_hidden_LabelSelector   *string                `protobuf:"bytes,6,opt,name=label_selector,json=labelSelector"`
	xxx_hidden_FieldSelector   *string                `protobuf:"bytes,7,opt,name=field_selector,json=fieldSelector"`
	xxx_hidden_ResourceVersion *string                `protobuf:"bytes,8,opt,name=resource_version,json=resourceVersion"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WatchRequest) GetCluster() string {
	if x != nil {
		if x.xxx_hidden_Cluster != nil {
			return *x.xxx_hidden_Cluster
		}
		return ""
	}
	return ""
}

func (x *WatchRequest) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *WatchRequest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *WatchRequest) GetResource() string {
	if x != nil {
		if x.xxx_hidden_Resource != nil {
			return *x.xxx_hidden_Resource
		}
		return ""
	}
	return ""
}

func (x *WatchRequest) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *WatchRequest) GetLabelSelector() string {
	if x != nil {
		if x.xxx_hidden_LabelSelector != nil {
			return *x.xxx_hidden_LabelSelector
		}
		return ""
	}
	return ""
}

func (x *WatchRequest) GetFieldSelector() string {
	if x != nil {
		if x.xxx_hidden_FieldSelector != nil {
			return *x.xxx_hidden_FieldSelector
		}
		return ""
	}
	return ""
}

func (x *WatchRequest) GetResourceVersion() string {
	if x != nil {
		if x.xxx_hidden_ResourceVersion != nil {
			return *x.xxx_hidden_ResourceVersion
		}
		return ""
	}
	return ""
}

func (x *WatchRequest) SetCluster(v string) {
	x.xxx_hidden_Cluster = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *WatchRequest) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *WatchRequest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *WatchRequest) SetResource(v string) {
	x.xxx_hidden_Resource = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *WatchRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *WatchRequest) SetLabelSelector(v string) {
	x.xxx_hidden_LabelSelector = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *WatchRequest) SetFieldSelector(v string) {
	x.xxx_hidden_FieldSelector = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *WatchRequest) SetResourceVersion(v string) {
	x.xxx_hidden_ResourceVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *WatchRequest) HasCluster() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *WatchRequest) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *WatchRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *WatchRequest) HasResource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *WatchRequest) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *WatchRequest) HasLabelSelector() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *WatchRequest) HasFieldSelector() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *WatchRequest) HasResourceVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *WatchRequest) ClearCluster() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cluster = nil
}

func (x *WatchRequest) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Group = nil
}

func (x *WatchRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Version = nil
}

func (x *WatchRequest) ClearResource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Resource = nil
}

func (x *WatchRequest) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Namespace = nil
}

func (x *WatchRequest) ClearLabelSelector() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_LabelSelector = nil
}

func (x *WatchRequest) ClearFieldSelector() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_FieldSelector = nil
}

func (x *WatchRequest) ClearResourceVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_ResourceVersion = nil
}

type WatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cluster       *string
	Group         *string
	Version       *string
	Resource      *string
	Namespace     *string
	LabelSelector *string
	FieldSelector *string
	// Start the watch from this specific resource version.
	ResourceVersion *string
}

func (b0 WatchRequest_builder) Build() *WatchRequest {
	m0 := &WatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cluster != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Cluster = b.Cluster
	}
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Group = b.Group
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Version = b.Version
	}
	if b.Resource != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Resource = b.Resource
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.LabelSelector != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_LabelSelector = b.LabelSelector
	}
	if b.FieldSelector != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_FieldSelector = b.FieldSelector
	}
	if b.ResourceVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_ResourceVersion = b.ResourceVersion
	}
	return m0
}

// WatchEvent represents a single change notification from the Kubernetes API.
type WatchEvent struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type            WatchEvent_Type        `protobuf:"varint,1,opt,name=type,enum=otterscale.resource.v1.WatchEvent_Type"`
	xxx_hidden_Resource        *Resource              `protobuf:"bytes,2,opt,name=resource"`
	xxx_hidden_ResourceVersion *string                `protobuf:"bytes,3,opt,name=resource_version,json=resourceVersion"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_api_resource_v1_resource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_v1_resource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WatchEvent) GetType() WatchEvent_Type {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return WatchEvent_TYPE_UNSPECIFIED
}

func (x *WatchEvent) GetResource() *Resource {
	if x != nil {
		return x.xxx_hidden_Resource
	}
	return nil
}

func (x *WatchEvent) GetResourceVersion() string {
	if x != nil {
		if x.xxx_hidden_ResourceVersion != nil {
			return *x.xxx_hidden_ResourceVersion
		}
		return ""
	}
	return ""
}

func (x *WatchEvent) SetType(v WatchEvent_Type) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *WatchEvent) SetResource(v *Resource) {
	x.xxx_hidden_Resource = v
}

func (x *WatchEvent) SetResourceVersion(v string) {
	x.xxx_hidden_ResourceVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *WatchEvent) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *WatchEvent) HasResource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Resource != nil
}

func (x *WatchEvent) HasResourceVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *WatchEvent) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = WatchEvent_TYPE_UNSPECIFIED
}

func (x *WatchEvent) ClearResource() {
	x.xxx_hidden_Resource = nil
}

func (x *WatchEvent) ClearResourceVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ResourceVersion = nil
}

type WatchEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The type of the watch event.
	Type *WatchEvent_Type
	// The state of the resource associated with the event.
	Resource *Resource
	// The resourceVersion of the watch event, used to initiate a Watch from a specific point in time.
	ResourceVersion *string
}

func (b0 WatchEvent_builder) Build() *WatchEvent {
	m0 := &WatchEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Type = *b.Type
	}
	x.xxx_hidden_Resource = b.Resource
	if b.ResourceVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ResourceVersion = b.ResourceVersion
	}
	return m0
}

var File_api_resource_v1_resource_proto protoreflect.FileDescriptor

const file_api_resource_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/resource/v1/resource.proto\x12\x16otterscale.resource.v1\x1a\x15api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc4\x01\n" +
	"\vAPIResource\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"namespaced\x18\x05 \x01(\bR\n" +
	"namespaced\x12\x14\n" +
	"\x05verbs\x18\x06 \x03(\tR\x05verbs\x12\x1f\n" +
	"\vshort_names\x18\a \x03(\tR\n" +
	"shortNames\",\n" +
	"\x10DiscoveryRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\"]\n" +
	"\x11DiscoveryResponse\x12H\n" +
	"\rapi_resources\x18\x01 \x03(\v2#.otterscale.resource.v1.APIResourceR\fapiResources\"m\n" +
	"\rSchemaRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\";\n" +
	"\bResource\x12/\n" +
	"\x06object\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06object\"\x91\x02\n" +
	"\vListRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12%\n" +
	"\x0elabel_selector\x18\x06 \x01(\tR\rlabelSelector\x12%\n" +
	"\x0efield_selector\x18\a \x01(\tR\rfieldSelector\x12\x14\n" +
	"\x05limit\x18\b \x01(\x03R\x05limit\x12\x1a\n" +
	"\bcontinue\x18\t \x01(\tR\bcontinue\"\xbf\x01\n" +
	"\fListResponse\x12)\n" +
	"\x10resource_version\x18\x01 \x01(\tR\x0fresourceVersion\x12\x1a\n" +
	"\bcontinue\x18\x02 \x01(\tR\bcontinue\x120\n" +
	"\x14remaining_item_count\x18\x03 \x01(\x03R\x12remainingItemCount\x126\n" +
	"\x05items\x18\x04 \x03(\v2 .otterscale.resource.v1.ResourceR\x05items\"\xa4\x01\n" +
	"\n" +
	"GetRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"\xaf\x01\n" +
	"\rCreateRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bmanifest\x18\x06 \x01(\fR\bmanifest\"\xfd\x01\n" +
	"\fApplyRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x1a\n" +
	"\bmanifest\x18\a \x01(\fR\bmanifest\x12\x14\n" +
	"\x05force\x18\b \x01(\bR\x05force\x12#\n" +
	"\rfield_manager\x18\t \x01(\tR\ffieldManager\"\xd9\x01\n" +
	"\rDeleteRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x120\n" +
	"\x14grace_period_seconds\x18\a \x01(\x03R\x12gracePeriodSeconds\"\x8b\x02\n" +
	"\fWatchRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12%\n" +
	"\x0elabel_selector\x18\x06 \x01(\tR\rlabelSelector\x12%\n" +
	"\x0efield_selector\x18\a \x01(\tR\rfieldSelector\x12)\n" +
	"\x10resource_version\x18\b \x01(\tR\x0fresourceVersion\"\xa8\x02\n" +
	"\n" +
	"WatchEvent\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.otterscale.resource.v1.WatchEvent.TypeR\x04type\x12<\n" +
	"\bresource\x18\x02 \x01(\v2 .otterscale.resource.v1.ResourceR\bresource\x12)\n" +
	"\x10resource_version\x18\x03 \x01(\tR\x0fresourceVersion\"t\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TYPE_ADDED\x10\x01\x12\x11\n" +
	"\rTYPE_MODIFIED\x10\x02\x12\x10\n" +
	"\fTYPE_DELETED\x10\x03\x12\x11\n" +
	"\rTYPE_BOOKMARK\x10\x04\x12\x0e\n" +
	"\n" +
	"TYPE_ERROR\x10\x052\xe7\x06\n" +
	"\x0fResourceService\x12y\n" +
	"\tDiscovery\x12(.otterscale.resource.v1.DiscoveryRequest\x1a).otterscale.resource.v1.DiscoveryResponse\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12a\n" +
	"\x06Schema\x12%.otterscale.resource.v1.SchemaRequest\x1a\x17.google.protobuf.Struct\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12j\n" +
	"\x04List\x12#.otterscale.resource.v1.ListRequest\x1a$.otterscale.resource.v1.ListResponse\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12d\n" +
	"\x03Get\x12\".otterscale.resource.v1.GetRequest\x1a .otterscale.resource.v1.Resource\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12j\n" +
	"\x06Create\x12%.otterscale.resource.v1.CreateRequest\x1a .otterscale.resource.v1.Resource\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12h\n" +
	"\x05Apply\x12$.otterscale.resource.v1.ApplyRequest\x1a .otterscale.resource.v1.Resource\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12`\n" +
	"\x06Delete\x12%.otterscale.resource.v1.DeleteRequest\x1a\x16.google.protobuf.Empty\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12l\n" +
	"\x05Watch\x12$.otterscale.resource.v1.WatchRequest\x1a\".otterscale.resource.v1.WatchEvent\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled0\x01B;Z9github.com/otterscale/otterscale-agent/api/resource/v1;pbb\beditionsp\xe9\a"

var file_api_resource_v1_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_resource_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_resource_v1_resource_proto_goTypes = []any{
	(WatchEvent_Type)(0),      // 0: otterscale.resource.v1.WatchEvent.Type
	(*APIResource)(nil),       // 1: otterscale.resource.v1.APIResource
	(*DiscoveryRequest)(nil),  // 2: otterscale.resource.v1.DiscoveryRequest
	(*DiscoveryResponse)(nil), // 3: otterscale.resource.v1.DiscoveryResponse
	(*SchemaRequest)(nil),     // 4: otterscale.resource.v1.SchemaRequest
	(*Resource)(nil),          // 5: otterscale.resource.v1.Resource
	(*ListRequest)(nil),       // 6: otterscale.resource.v1.ListRequest
	(*ListResponse)(nil),      // 7: otterscale.resource.v1.ListResponse
	(*GetRequest)(nil),        // 8: otterscale.resource.v1.GetRequest
	(*CreateRequest)(nil),     // 9: otterscale.resource.v1.CreateRequest
	(*ApplyRequest)(nil),      // 10: otterscale.resource.v1.ApplyRequest
	(*DeleteRequest)(nil),     // 11: otterscale.resource.v1.DeleteRequest
	(*WatchRequest)(nil),      // 12: otterscale.resource.v1.WatchRequest
	(*WatchEvent)(nil),        // 13: otterscale.resource.v1.WatchEvent
	(*structpb.Struct)(nil),   // 14: google.protobuf.Struct
	(*emptypb.Empty)(nil),     // 15: google.protobuf.Empty
}
var file_api_resource_v1_resource_proto_depIdxs = []int32{
	1,  // 0: otterscale.resource.v1.DiscoveryResponse.api_resources:type_name -> otterscale.resource.v1.APIResource
	14, // 1: otterscale.resource.v1.Resource.object:type_name -> google.protobuf.Struct
	5,  // 2: otterscale.resource.v1.ListResponse.items:type_name -> otterscale.resource.v1.Resource
	0,  // 3: otterscale.resource.v1.WatchEvent.type:type_name -> otterscale.resource.v1.WatchEvent.Type
	5,  // 4: otterscale.resource.v1.WatchEvent.resource:type_name -> otterscale.resource.v1.Resource
	2,  // 5: otterscale.resource.v1.ResourceService.Discovery:input_type -> otterscale.resource.v1.DiscoveryRequest
	4,  // 6: otterscale.resource.v1.ResourceService.Schema:input_type -> otterscale.resource.v1.SchemaRequest
	6,  // 7: otterscale.resource.v1.ResourceService.List:input_type -> otterscale.resource.v1.ListRequest
	8,  // 8: otterscale.resource.v1.ResourceService.Get:input_type -> otterscale.resource.v1.GetRequest
	9,  // 9: otterscale.resource.v1.ResourceService.Create:input_type -> otterscale.resource.v1.CreateRequest
	10, // 10: otterscale.resource.v1.ResourceService.Apply:input_type -> otterscale.resource.v1.ApplyRequest
	11, // 11: otterscale.resource.v1.ResourceService.Delete:input_type -> otterscale.resource.v1.DeleteRequest
	12, // 12: otterscale.resource.v1.ResourceService.Watch:input_type -> otterscale.resource.v1.WatchRequest
	3,  // 13: otterscale.resource.v1.ResourceService.Discovery:output_type -> otterscale.resource.v1.DiscoveryResponse
	14, // 14: otterscale.resource.v1.ResourceService.Schema:output_type -> google.protobuf.Struct
	7,  // 15: otterscale.resource.v1.ResourceService.List:output_type -> otterscale.resource.v1.ListResponse
	5,  // 16: otterscale.resource.v1.ResourceService.Get:output_type -> otterscale.resource.v1.Resource
	5,  // 17: otterscale.resource.v1.ResourceService.Create:output_type -> otterscale.resource.v1.Resource
	5,  // 18: otterscale.resource.v1.ResourceService.Apply:output_type -> otterscale.resource.v1.Resource
	15, // 19: otterscale.resource.v1.ResourceService.Delete:output_type -> google.protobuf.Empty
	13, // 20: otterscale.resource.v1.ResourceService.Watch:output_type -> otterscale.resource.v1.WatchEvent
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_resource_v1_resource_proto_init() }
func file_api_resource_v1_resource_proto_init() {
	if File_api_resource_v1_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_resource_v1_resource_proto_rawDesc), len(file_api_resource_v1_resource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_resource_v1_resource_proto_goTypes,
		DependencyIndexes: file_api_resource_v1_resource_proto_depIdxs,
		EnumInfos:         file_api_resource_v1_resource_proto_enumTypes,
		MessageInfos:      file_api_resource_v1_resource_proto_msgTypes,
	}.Build()
	File_api_resource_v1_resource_proto = out.File
	file_api_resource_v1_resource_proto_goTypes = nil
	file_api_resource_v1_resource_proto_depIdxs = nil
}
