// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/resource/v1/resource.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/otterscale/otterscale-agent/api/resource/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ResourceServiceName is the fully-qualified name of the ResourceService service.
	ResourceServiceName = "otterscale.resource.v1.ResourceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ResourceServiceDiscoveryProcedure is the fully-qualified name of the ResourceService's Discovery
	// RPC.
	ResourceServiceDiscoveryProcedure = "/otterscale.resource.v1.ResourceService/Discovery"
	// ResourceServiceSchemaProcedure is the fully-qualified name of the ResourceService's Schema RPC.
	ResourceServiceSchemaProcedure = "/otterscale.resource.v1.ResourceService/Schema"
	// ResourceServiceListProcedure is the fully-qualified name of the ResourceService's List RPC.
	ResourceServiceListProcedure = "/otterscale.resource.v1.ResourceService/List"
	// ResourceServiceGetProcedure is the fully-qualified name of the ResourceService's Get RPC.
	ResourceServiceGetProcedure = "/otterscale.resource.v1.ResourceService/Get"
	// ResourceServiceCreateProcedure is the fully-qualified name of the ResourceService's Create RPC.
	ResourceServiceCreateProcedure = "/otterscale.resource.v1.ResourceService/Create"
	// ResourceServiceApplyProcedure is the fully-qualified name of the ResourceService's Apply RPC.
	ResourceServiceApplyProcedure = "/otterscale.resource.v1.ResourceService/Apply"
	// ResourceServiceDeleteProcedure is the fully-qualified name of the ResourceService's Delete RPC.
	ResourceServiceDeleteProcedure = "/otterscale.resource.v1.ResourceService/Delete"
	// ResourceServiceWatchProcedure is the fully-qualified name of the ResourceService's Watch RPC.
	ResourceServiceWatchProcedure = "/otterscale.resource.v1.ResourceService/Watch"
)

// ResourceServiceClient is a client for the otterscale.resource.v1.ResourceService service.
type ResourceServiceClient interface {
	// Discovery retrieves the available API resources in the specified cluster.
	Discovery(context.Context, *v1.DiscoveryRequest) (*v1.DiscoveryResponse, error)
	// Schema retrieves the structural definition (JSON Schema) for a specific resource type.
	// It supports both native Kubernetes resources and installed CRDs.
	// The raw JSON Schema (Draft 4/7 or 2020-12) describing the resource structure.
	// This is typically derived from Kubernetes OpenAPIV3Schema.
	Schema(context.Context, *v1.SchemaRequest) (*structpb.Struct, error)
	// List retrieves a collection of resources based on the provided GVR and filters.
	List(context.Context, *v1.ListRequest) (*v1.ListResponse, error)
	// Get retrieves a single resource by its name within a namespace.
	Get(context.Context, *v1.GetRequest) (*v1.Resource, error)
	// Create creates a new resource in the cluster using the provided manifest.
	Create(context.Context, *v1.CreateRequest) (*v1.Resource, error)
	// Apply performs a Server-Side Apply (SSA) to update or create a resource.
	// This is the recommended way to perform partial updates.
	Apply(context.Context, *v1.ApplyRequest) (*v1.Resource, error)
	// Delete removes a resource from the cluster by its name.
	Delete(context.Context, *v1.DeleteRequest) (*emptypb.Empty, error)
	// Watch initiates a server-side stream to monitor resource changes in real-time.
	Watch(context.Context, *v1.WatchRequest) (*connect.ServerStreamForClient[v1.WatchEvent], error)
}

// NewResourceServiceClient constructs a client for the otterscale.resource.v1.ResourceService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewResourceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ResourceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	resourceServiceMethods := v1.File_api_resource_v1_resource_proto.Services().ByName("ResourceService").Methods()
	return &resourceServiceClient{
		discovery: connect.NewClient[v1.DiscoveryRequest, v1.DiscoveryResponse](
			httpClient,
			baseURL+ResourceServiceDiscoveryProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("Discovery")),
			connect.WithClientOptions(opts...),
		),
		schema: connect.NewClient[v1.SchemaRequest, structpb.Struct](
			httpClient,
			baseURL+ResourceServiceSchemaProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("Schema")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+ResourceServiceListProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[v1.GetRequest, v1.Resource](
			httpClient,
			baseURL+ResourceServiceGetProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[v1.CreateRequest, v1.Resource](
			httpClient,
			baseURL+ResourceServiceCreateProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		apply: connect.NewClient[v1.ApplyRequest, v1.Resource](
			httpClient,
			baseURL+ResourceServiceApplyProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("Apply")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.DeleteRequest, emptypb.Empty](
			httpClient,
			baseURL+ResourceServiceDeleteProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.WatchRequest, v1.WatchEvent](
			httpClient,
			baseURL+ResourceServiceWatchProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// resourceServiceClient implements ResourceServiceClient.
type resourceServiceClient struct {
	discovery *connect.Client[v1.DiscoveryRequest, v1.DiscoveryResponse]
	schema    *connect.Client[v1.SchemaRequest, structpb.Struct]
	list      *connect.Client[v1.ListRequest, v1.ListResponse]
	get       *connect.Client[v1.GetRequest, v1.Resource]
	create    *connect.Client[v1.CreateRequest, v1.Resource]
	apply     *connect.Client[v1.ApplyRequest, v1.Resource]
	delete    *connect.Client[v1.DeleteRequest, emptypb.Empty]
	watch     *connect.Client[v1.WatchRequest, v1.WatchEvent]
}

// Discovery calls otterscale.resource.v1.ResourceService.Discovery.
func (c *resourceServiceClient) Discovery(ctx context.Context, req *v1.DiscoveryRequest) (*v1.DiscoveryResponse, error) {
	response, err := c.discovery.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Schema calls otterscale.resource.v1.ResourceService.Schema.
func (c *resourceServiceClient) Schema(ctx context.Context, req *v1.SchemaRequest) (*structpb.Struct, error) {
	response, err := c.schema.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// List calls otterscale.resource.v1.ResourceService.List.
func (c *resourceServiceClient) List(ctx context.Context, req *v1.ListRequest) (*v1.ListResponse, error) {
	response, err := c.list.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Get calls otterscale.resource.v1.ResourceService.Get.
func (c *resourceServiceClient) Get(ctx context.Context, req *v1.GetRequest) (*v1.Resource, error) {
	response, err := c.get.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Create calls otterscale.resource.v1.ResourceService.Create.
func (c *resourceServiceClient) Create(ctx context.Context, req *v1.CreateRequest) (*v1.Resource, error) {
	response, err := c.create.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Apply calls otterscale.resource.v1.ResourceService.Apply.
func (c *resourceServiceClient) Apply(ctx context.Context, req *v1.ApplyRequest) (*v1.Resource, error) {
	response, err := c.apply.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Delete calls otterscale.resource.v1.ResourceService.Delete.
func (c *resourceServiceClient) Delete(ctx context.Context, req *v1.DeleteRequest) (*emptypb.Empty, error) {
	response, err := c.delete.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Watch calls otterscale.resource.v1.ResourceService.Watch.
func (c *resourceServiceClient) Watch(ctx context.Context, req *v1.WatchRequest) (*connect.ServerStreamForClient[v1.WatchEvent], error) {
	return c.watch.CallServerStream(ctx, connect.NewRequest(req))
}

// ResourceServiceHandler is an implementation of the otterscale.resource.v1.ResourceService
// service.
type ResourceServiceHandler interface {
	// Discovery retrieves the available API resources in the specified cluster.
	Discovery(context.Context, *v1.DiscoveryRequest) (*v1.DiscoveryResponse, error)
	// Schema retrieves the structural definition (JSON Schema) for a specific resource type.
	// It supports both native Kubernetes resources and installed CRDs.
	// The raw JSON Schema (Draft 4/7 or 2020-12) describing the resource structure.
	// This is typically derived from Kubernetes OpenAPIV3Schema.
	Schema(context.Context, *v1.SchemaRequest) (*structpb.Struct, error)
	// List retrieves a collection of resources based on the provided GVR and filters.
	List(context.Context, *v1.ListRequest) (*v1.ListResponse, error)
	// Get retrieves a single resource by its name within a namespace.
	Get(context.Context, *v1.GetRequest) (*v1.Resource, error)
	// Create creates a new resource in the cluster using the provided manifest.
	Create(context.Context, *v1.CreateRequest) (*v1.Resource, error)
	// Apply performs a Server-Side Apply (SSA) to update or create a resource.
	// This is the recommended way to perform partial updates.
	Apply(context.Context, *v1.ApplyRequest) (*v1.Resource, error)
	// Delete removes a resource from the cluster by its name.
	Delete(context.Context, *v1.DeleteRequest) (*emptypb.Empty, error)
	// Watch initiates a server-side stream to monitor resource changes in real-time.
	Watch(context.Context, *v1.WatchRequest, *connect.ServerStream[v1.WatchEvent]) error
}

// NewResourceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewResourceServiceHandler(svc ResourceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	resourceServiceMethods := v1.File_api_resource_v1_resource_proto.Services().ByName("ResourceService").Methods()
	resourceServiceDiscoveryHandler := connect.NewUnaryHandlerSimple(
		ResourceServiceDiscoveryProcedure,
		svc.Discovery,
		connect.WithSchema(resourceServiceMethods.ByName("Discovery")),
		connect.WithHandlerOptions(opts...),
	)
	resourceServiceSchemaHandler := connect.NewUnaryHandlerSimple(
		ResourceServiceSchemaProcedure,
		svc.Schema,
		connect.WithSchema(resourceServiceMethods.ByName("Schema")),
		connect.WithHandlerOptions(opts...),
	)
	resourceServiceListHandler := connect.NewUnaryHandlerSimple(
		ResourceServiceListProcedure,
		svc.List,
		connect.WithSchema(resourceServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	resourceServiceGetHandler := connect.NewUnaryHandlerSimple(
		ResourceServiceGetProcedure,
		svc.Get,
		connect.WithSchema(resourceServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	resourceServiceCreateHandler := connect.NewUnaryHandlerSimple(
		ResourceServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(resourceServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	resourceServiceApplyHandler := connect.NewUnaryHandlerSimple(
		ResourceServiceApplyProcedure,
		svc.Apply,
		connect.WithSchema(resourceServiceMethods.ByName("Apply")),
		connect.WithHandlerOptions(opts...),
	)
	resourceServiceDeleteHandler := connect.NewUnaryHandlerSimple(
		ResourceServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(resourceServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	resourceServiceWatchHandler := connect.NewServerStreamHandlerSimple(
		ResourceServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(resourceServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/otterscale.resource.v1.ResourceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ResourceServiceDiscoveryProcedure:
			resourceServiceDiscoveryHandler.ServeHTTP(w, r)
		case ResourceServiceSchemaProcedure:
			resourceServiceSchemaHandler.ServeHTTP(w, r)
		case ResourceServiceListProcedure:
			resourceServiceListHandler.ServeHTTP(w, r)
		case ResourceServiceGetProcedure:
			resourceServiceGetHandler.ServeHTTP(w, r)
		case ResourceServiceCreateProcedure:
			resourceServiceCreateHandler.ServeHTTP(w, r)
		case ResourceServiceApplyProcedure:
			resourceServiceApplyHandler.ServeHTTP(w, r)
		case ResourceServiceDeleteProcedure:
			resourceServiceDeleteHandler.ServeHTTP(w, r)
		case ResourceServiceWatchProcedure:
			resourceServiceWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedResourceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedResourceServiceHandler struct{}

func (UnimplementedResourceServiceHandler) Discovery(context.Context, *v1.DiscoveryRequest) (*v1.DiscoveryResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otterscale.resource.v1.ResourceService.Discovery is not implemented"))
}

func (UnimplementedResourceServiceHandler) Schema(context.Context, *v1.SchemaRequest) (*structpb.Struct, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otterscale.resource.v1.ResourceService.Schema is not implemented"))
}

func (UnimplementedResourceServiceHandler) List(context.Context, *v1.ListRequest) (*v1.ListResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otterscale.resource.v1.ResourceService.List is not implemented"))
}

func (UnimplementedResourceServiceHandler) Get(context.Context, *v1.GetRequest) (*v1.Resource, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otterscale.resource.v1.ResourceService.Get is not implemented"))
}

func (UnimplementedResourceServiceHandler) Create(context.Context, *v1.CreateRequest) (*v1.Resource, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otterscale.resource.v1.ResourceService.Create is not implemented"))
}

func (UnimplementedResourceServiceHandler) Apply(context.Context, *v1.ApplyRequest) (*v1.Resource, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otterscale.resource.v1.ResourceService.Apply is not implemented"))
}

func (UnimplementedResourceServiceHandler) Delete(context.Context, *v1.DeleteRequest) (*emptypb.Empty, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otterscale.resource.v1.ResourceService.Delete is not implemented"))
}

func (UnimplementedResourceServiceHandler) Watch(context.Context, *v1.WatchRequest, *connect.ServerStream[v1.WatchEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("otterscale.resource.v1.ResourceService.Watch is not implemented"))
}
