// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/annotations.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Feature struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_api_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_api_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Feature) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Feature) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Feature) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Feature) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type Feature_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 Feature_builder) Build() *Feature {
	m0 := &Feature{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

var file_api_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Feature)(nil),
		Field:         7777777,
		Name:          "otterscale.api.feature",
		Tag:           "bytes,7777777,opt,name=feature",
		Filename:      "api/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional otterscale.api.Feature feature = 7777777;
	E_Feature = &file_api_annotations_proto_extTypes[0]
)

var File_api_annotations_proto protoreflect.FileDescriptor

const file_api_annotations_proto_rawDesc = "" +
	"\n" +
	"\x15api/annotations.proto\x12\x0eotterscale.api\x1a google/protobuf/descriptor.proto\"\x1d\n" +
	"\aFeature\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:T\n" +
	"\afeature\x12\x1e.google.protobuf.MethodOptions\x18\xf1\xdb\xda\x03 \x01(\v2\x17.otterscale.api.FeatureR\afeatureB0Z.github.com/otterscale/otterscale-agent/api;apib\beditionsp\xe8\a"

var file_api_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_annotations_proto_goTypes = []any{
	(*Feature)(nil),                    // 0: otterscale.api.Feature
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_api_annotations_proto_depIdxs = []int32{
	1, // 0: otterscale.api.feature:extendee -> google.protobuf.MethodOptions
	0, // 1: otterscale.api.feature:type_name -> otterscale.api.Feature
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_annotations_proto_init() }
func file_api_annotations_proto_init() {
	if File_api_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_annotations_proto_rawDesc), len(file_api_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_api_annotations_proto_goTypes,
		DependencyIndexes: file_api_annotations_proto_depIdxs,
		MessageInfos:      file_api_annotations_proto_msgTypes,
		ExtensionInfos:    file_api_annotations_proto_extTypes,
	}.Build()
	File_api_annotations_proto = out.File
	file_api_annotations_proto_goTypes = nil
	file_api_annotations_proto_depIdxs = nil
}
